{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
{{- end }}

---

{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          resources:
            {{- toYaml .Values.chatbot.resources | nindent 12 }} 
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.envFrom.secret | quote }}
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.envFrom.secret | quote }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.envFrom.secret | quote }}
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: {{ .Values.postgres.envFrom.PGDATA | quote }}
          volumeMounts:
            - name: pvc-{{ include "chatbot.fullname" . }}-postgres
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pvc-{{ include "chatbot.fullname" . }}-postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
{{- end }}
