apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.chatbot.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.chatbot.service.type }}
  ports:
    - port: {{ .Values.chatbot.service.port }}
      targetPort: {{ .Values.chatbot.service.port }}
      name: http
  selector:
    app.kubernetes.io/component: chatbot
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ tpl .Values.chatbot.ingress.host $ }}
      secretName: {{ tpl .Values.chatbot.ingress.tlsSecret $ }}
  rules:
    - host: {{ tpl .Values.chatbot.ingress.host $ }}
      http:
        paths:
          - path: {{ .Values.chatbot.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.fullname" . }}-chatbot
                port:
                  number: {{ .Values.chatbot.service.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: chatbot
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-chatbot
  replicas: {{ .Values.chatbot.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: chatbot
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: chatbot
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chatbot
          image: io2060/hologram-generic-ai-agent-app:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.chatbot.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.chatbot.service.port }}
              name: http
          resources:
            {{- toYaml .Values.chatbot.resources | nindent 12 }}
          env:
            {{- range .Values.chatbot.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
            {{- range $key, $val := .Values.chatbot.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name:  chatbot-secret
                  key: {{ $key }}
            {{- end }}
          volumeMounts:
            - name: pvc-{{ include "chatbot.fullname" . }}-chatbot
              mountPath: /app/rag/docs
  volumeClaimTemplates:
    - metadata:
        name: pvc-{{ include "chatbot.fullname" . }}-chatbot
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.chatbot.storage.size }}