apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.chatbot.envFrom.configMap | quote }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.chatbot.config }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chatbot.envFrom.secret | quote }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.chatbot.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.chatbot.service.type }}
  ports:
    - port: {{ .Values.chatbot.service.port }}
      targetPort: {{ .Values.chatbot.service.port }}
      name: http
  selector:
    app.kubernetes.io/component: chatbot
    {{- include "chatbot.selectorLabels" . | nindent 4 }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ tpl .Values.chatbot.ingress.host $ }}
      secretName: {{ tpl .Values.chatbot.ingress.tlsSecret $ }}
  rules:
    - host: {{ tpl .Values.chatbot.ingress.host $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.fullname" . }}-chatbot
                port:
                  number: {{ .Values.chatbot.service.port }}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-chatbot
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: chatbot
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-chatbot
  replicas: {{ .Values.chatbot.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: chatbot
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: chatbot
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chatbot
          image: "{{ .Values.chatbot.image.repository }}:{{ .Values.chatbot.image.tag }}"
          resources:
            {{- toYaml .Values.chatbot.resources | nindent 12 }} 
          imagePullPolicy: {{ .Values.chatbot.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.chatbot.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Values.chatbot.envFrom.configMap | quote }}
            - secretRef:
                name: {{ .Values.chatbot.envFrom.secret | quote }}  
          volumeMounts:
            - name: pvc-{{ include "chatbot.fullname" . }}-chatbot
              mountPath: /app/rag/docs
  volumeClaimTemplates:
    - metadata:
        name: pvc-{{ include "chatbot.fullname" . }}-chatbot
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.chatbot.storage.size }}
