apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.postgres.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.selectorLabels" . | nindent 4 }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "postgres:15.2"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          env:
            {{- range .Values.postgres.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range $key, $val := .Values.postgres.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name:  postgres-secret
                  key: {{ $key }}
            {{- end }}
          volumeMounts:
            - name: pvc-{{ include "chatbot.fullname" . }}-postgres
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pvc-{{ include "chatbot.fullname" . }}-postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
