apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vsAgent.envFrom.configMap | quote }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.vsAgent.config }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vsAgent.envFrom.secret | quote }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.vsAgent.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot.fullname" . }}-vs-agent
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ tpl .Values.vsAgent.ingress.host $ }}
      secretName: {{ tpl .Values.vsAgent.ingress.tlsSecret $ }}
  rules:
    - host: {{ tpl .Values.vsAgent.ingress.host $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.fullname" . }}-vs-agent
                port:
                  number: {{ .Values.vsAgent.service.ports.http }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-vs-agent
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.vsAgent.service.type }}
  ports:
    - port: {{ .Values.vsAgent.service.ports.http }}
      targetPort: {{ .Values.vsAgent.service.ports.http }}
      name: http
    - port: {{ .Values.vsAgent.service.ports.ws }}
      targetPort: {{ .Values.vsAgent.service.ports.ws }}
      name: ws
  selector:
    app.kubernetes.io/component: vs-agent
    {{- include "chatbot.selectorLabels" . | nindent 4 }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-vs-agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: vs-agent
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-vs-agent
  replicas: {{ .Values.vsAgent.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: vs-agent
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vs-agent
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vs-agent
          image: "{{ .Values.vsAgent.image.repository }}:{{ .Values.vsAgent.image.tag }}"
          resources:
            {{- toYaml .Values.chatbot.resources | nindent 12 }} 
          imagePullPolicy: {{ .Values.vsAgent.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.vsAgent.service.ports.http }}
              name: http
            - containerPort: {{ .Values.vsAgent.service.ports.ws }}
              name: ws
          envFrom:
            - configMapRef:
                name: {{ .Values.vsAgent.envFrom.configMap | quote }}
            - secretRef:
                name: {{ .Values.vsAgent.envFrom.secret | quote }}
