namespace: demos

global:
  imagePullPolicy: Always

redis:
  enabled: true
  image: redis/redis-stack-server:latest
  port: 6379
  resources:
    requests:
      cpu: '50m'
      memory: '64Mi'
    limits:
      cpu: '200m'
      memory: '256Mi'
  service:
    type: ClusterIP
  persistence:
    enabled: true
    mountPath: /data
    accessModes:
      - ReadWriteOnce
    size: 1Gi

chatbot:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: '100m'
      memory: '128Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  image:
    repository: io2060/hologram-welcome-ai-agent
    tag: latest
    pullPolicy: Always
  envFrom:
    configMap: hologram-welcome-chatbot-config
    secret: hologram-welcome-chatbot-secret
  service:
    type: ClusterIP
    port: 3003
  storage:
    size: 1Gi
  ingress:
    enabled: true
    className: nginx
    host: hw-c.demos.dev.2060.io
    tlsSecret: hw-c.demos.dev.2060.io-cert
    path: /
    tls: false

vsAgent:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: '100m'
      memory: '128Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  image:
    repository: io2060/vs-agent
    tag: v1.3.0
    pullPolicy: Always
  envFrom:
    configMap: hologram-welcome-vs-agent-config
    secret: hologram-welcome-vs-agent-secret
  service:
    type: ClusterIP
    ports:
      http: 3001
      ws: 3000
  ingress:
    enabled: true
    className: nginx
    host: hologram-welcome.demos.dev.2060.io
    tlsSecret: hologram-welcome.demos.dev.2060.io-cert
    tls: true

postgres:
  enabled: true
  image: postgres:15.2
  port: 5432
  resources:
    requests:
      cpu: '200m'
      memory: '256Mi'
    limits:
      cpu: '1000m'
      memory: '1024Mi'
  envFrom:
    secret: hologram-welcome-postgres-secret
    PGDATA: '/var/lib/postgresql/data/pgdata'
  service:
    type: ClusterIP
  storage:
    size: 10Gi
    storageClassName: ''

stats:
  enabled: true
  replicaCount: 1
  image:
    repository: mobiera/stats
    tag: main
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8700
  envFrom:
    configMap: hologram-welcome-stats-config
    secret: hologram-welcome-stats-secret
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  ingress:
    enabled: true
    host: hw-stats.demos.dev.2060.io
    tlsSecret: hw-stats.demos.dev.2060.io-cert

artemis:
  enabled: true
  image:
    repository: apache/activemq-artemis
    tag: '2.41.0'
    pullPolicy: Always
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      core: 61616
      web: 8161
  envFrom:
    secret: hologram-welcome-artemis-secret
  resources:
    requests:
      cpu: '100m'
      memory: '256Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  storage:
    size: 2Gi
    mountPath: /var/lib/artemis-instance
